requires 'Moose';
requires 'Bread::Board';
requires 'Plack';
requires 'Web::Request';
requires 'Web::Request::Role::JSON';
requires 'Web::Request::Role::Response';
requires 'Bread::Runner';
requires 'Net::Async::HTTP::Server';
requires 'Log::Any';
requires 'Throwable::X';
requires 'Router::Simple';
requires 'Plack::Middleware::PrettyException'
